"""Async Playwright scraper.

Responsibilities
  * Open a managed browser (one per `Scraper` instance).
  * Decide HTML vs PDF based on URL extension and HTTP `Content-Type`.
  * For HTML: navigate, wait for network idle, strip boilerplate, return
    cleaned text + raw HTML.
  * For PDFs: download via Playwright's `APIRequestContext` (carries the
    browser's cookies/UA) and extract text with `pypdf`.
  * Apply a hard char cap so a 10MB page can't blow up our token budget.

We deliberately surface a simple `FetchResult` dataclass to the rest of
the pipeline so `extractor.py` doesn't need to know about Playwright.
"""

from __future__ import annotations

import asyncio
import io
import re
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Optional
from urllib.parse import urlparse

from bs4 import BeautifulSoup
from playwright.async_api import (
    Browser,
    BrowserContext,
    Frame,
    Page,
    Playwright,
    TimeoutError as PlaywrightTimeoutError,
    async_playwright,
)
from pypdf import PdfReader
from pypdf.errors import PdfReadError
from tenacity import (
    AsyncRetrying,
    RetryError,
    retry_if_exception_type,
    stop_after_attempt,
    wait_exponential,
)

from config import get_settings
from logging_setup import get_logger

logger = get_logger(__name__)


# Tags whose content we strip before sending HTML upstream. We
# deliberately keep this list MINIMAL — only truly content-free
# elements. On a typical blog this is too lenient, but municipal
# portals routinely put real content inside `<form>`, `<nav>`,
# `<header>`, `<footer>`, and `<aside>`:
#   * ASP.NET WebForms (eTRAKiT, Munis, etc.) wrap the whole page in
#     a single `<form runat="server">`.
#   * Permit dashboards put their navigation sidebar (with quick links
#     like "Search Permit", "Pay Fees") inside `<nav>`.
#   * Many city sites put announcements / open-meeting notices in
#     `<aside>` or `<header>`.
# Token cost is bounded by `SCRAPER_MAX_HTML_CHARS`, so over-keeping is
# cheaper than wrongly stripping a critical signal.
_BOILERPLATE_TAGS = ("script", "style", "noscript", "svg")


# ---- eTRAKiT (CRW Systems) selectors -----------------------------------
#
# eTRAKiT is a widely-deployed permit/inspection portal used by ~hundreds
# of US municipalities. The control IDs are auto-generated by ASP.NET so
# we anchor on substring/suffix matches that survive page-template
# revisions, rather than full ids like `ctl00_cplMain_btnSearch_btn`.

_ETRAKIT_URL_MARKERS = ("/etrakit/", "/etrakit3/")

# Candidate selectors for the "Search" submit button, tried in order.
# CSS `:is(...)` would be nicer but Playwright handles a comma-list fine
# and falls through to the next selector if the first errors out.
_ETRAKIT_SEARCH_BUTTON_SELECTORS = (
    "input[id*='btnSearch']:not([disabled])",
    "a[id*='btnSearch']:not([aria-disabled='true'])",
    "input[type='submit'][value='Search']",
    "button:has-text('Search')",
)

# Candidate selectors for the "Search By" dropdown (only used as fallback
# when the default-wildcard click leaves results empty).
_ETRAKIT_SEARCH_BY_SELECTORS = (
    "select[id*='ddSearchBy']",
    "select[id*='cboSearchBy']",
    "select[name*='SearchBy']",
)

# Candidate selectors for the "Search Operator" dropdown
# (Begins With / Contains / Equals / At Least / At Most).
_ETRAKIT_OPERATOR_SELECTORS = (
    "select[id*='ddSearchOper']",
    "select[id*='ddOperator']",
    "select[id*='cboOperator']",
    "select[name*='Operator']",
)

# Candidate selectors for the "Search Value" text input.
_ETRAKIT_SEARCH_INPUT_SELECTORS = (
    "input[id*='txtSearchString']",
    "input[id*='txtSearchValue']",
    "input[id*='SearchValue']",
    "input[id*='txtSrchVal']",
)

# Selectors that indicate the results grid has rendered. We require
# `tr:has(td)` (a row with at least one data cell) to filter out form
# layout tables and header-only rows that fire too early. We also
# include `div[id*='SearchResults']:visible` because Frisco-style
# eTRAKiT leaves the results <div> in the DOM at page load with
# `display: none` and only unhides it after a successful search.
_ETRAKIT_RESULTS_SELECTOR = ", ".join((
    "div[id*='SearchResults']:visible",
    "table[id*='rgSearchRslts'] tr:has(td)",   # Telerik RadGrid (newer eTRAKiT)
    "table[id*='SearchResults'] tr:has(td)",
    "table[id*='gvResults'] tr:has(td)",
    "table[id*='dgPermit'] tr:has(td)",
    "div[id*='SearchResults'] table tr:has(td)",
))

# Selectors that indicate "no results" / "0 records" — also a valid
# terminal state for the interaction (search ran, just nothing matched).
_ETRAKIT_EMPTY_SELECTOR = (
    "[id*='lblNoRecords'], [id*='lblNoResults'], "
    "[id*='lblNoSearchRslts'], .RadGrid_NoRecords"
)

# Frisco-style eTRAKiT renders the empty state as visible body text
# rather than tagging it with a stable id. Match those phrases via
# Playwright's case-insensitive text engine.
_ETRAKIT_EMPTY_TEXT_SELECTORS = (
    "text=/There were no results to match/i",
    "text=/No records (were )?found/i",
    "text=/0 records found/i",
)


@dataclass(slots=True)
class FetchResult:
    """Output of a single fetch attempt, ready for the extractor."""

    url: str
    final_url: str
    content_type: str  # "html" | "pdf"
    text: str          # cleaned text suitable for the LLM
    raw_length: int    # length before truncation, for telemetry


@dataclass(slots=True)
class EtrakitSearchParams:
    """Parameterised query to drive the eTRAKiT search form.

    All fields are optional. Common combinations:
      * `search_value` alone -> blank-click wildcard search (existing
        behaviour). Used when neither dropdown matters.
      * `search_by` + `search_value` -> e.g. PERMIT NO = "B26-".
      * All three -> e.g. PERMIT NO + Contains + "B26-" on Frisco.
    """

    search_by: Optional[str] = None
    search_operator: Optional[str] = None
    search_value: Optional[str] = None

    def is_active(self) -> bool:
        """True if any parameter is set; False means 'click Search as-is'."""
        return any((self.search_by, self.search_operator, self.search_value))


class ScrapeError(RuntimeError):
    """Raised when a URL cannot be fetched after retries."""


class Scraper:
    """Async context-managed Playwright scraper.

    Use as::

        async with Scraper() as scraper:
            result = await scraper.fetch(url)
    """

    def __init__(self) -> None:
        self._settings = get_settings()
        self._pw: Optional[Playwright] = None
        self._browser: Optional[Browser] = None
        self._context: Optional[BrowserContext] = None

    # ---- lifecycle -----------------------------------------------------

    async def __aenter__(self) -> "Scraper":
        self._pw = await async_playwright().start()
        self._browser = await self._pw.chromium.launch(headless=self._settings.scraper_headless)
        self._context = await self._browser.new_context(
            user_agent=self._settings.scraper_user_agent,
            viewport={"width": 1366, "height": 900},
            locale="en-US",
            ignore_https_errors=True,
        )
        self._context.set_default_navigation_timeout(self._settings.scraper_nav_timeout_ms)
        logger.info("Playwright Chromium launched (headless=%s)", self._settings.scraper_headless)
        return self

    async def __aexit__(self, exc_type, exc, tb) -> None:
        if self._context:
            await self._context.close()
        if self._browser:
            await self._browser.close()
        if self._pw:
            await self._pw.stop()
        logger.info("Playwright shut down")

    # ---- public API ----------------------------------------------------

    async def fetch(
        self, url: str, *, etrakit_search: Optional[EtrakitSearchParams] = None,
    ) -> FetchResult:
        """Fetch a single URL with retries; returns a `FetchResult`.

        Pass `etrakit_search` to drive the search form on an eTRAKiT
        portal (no effect on non-eTRAKiT URLs).
        """
        try:
            async for attempt in AsyncRetrying(
                stop=stop_after_attempt(3),
                wait=wait_exponential(multiplier=2, min=2, max=20),
                retry=retry_if_exception_type((PlaywrightTimeoutError, asyncio.TimeoutError)),
                reraise=True,
            ):
                with attempt:
                    return await self._fetch_once(url, etrakit_search=etrakit_search)
        except RetryError as e:
            raise ScrapeError(f"Exhausted retries fetching {url}") from e
        except PlaywrightTimeoutError as e:
            raise ScrapeError(f"Timeout fetching {url}") from e
        # Should never get here because reraise=True, but appease mypy:
        raise ScrapeError(f"Unknown failure fetching {url}")

    # ---- internals -----------------------------------------------------

    async def _fetch_once(
        self, url: str, *, etrakit_search: Optional[EtrakitSearchParams] = None,
    ) -> FetchResult:
        """Dispatch a single URL to the PDF or HTML path."""
        assert self._context is not None, "Scraper must be used via `async with`."

        # Direct-PDF fast path: skip the full browser pipeline.
        if urlparse(url).path.lower().endswith(".pdf"):
            return await self._fetch_pdf(url)

        return await self._fetch_html(url, etrakit_search=etrakit_search)

    async def _fetch_html(
        self, url: str, *, etrakit_search: Optional[EtrakitSearchParams] = None,
    ) -> FetchResult:
        """Render `url` in Chromium and return cleaned text.

        Recognises eTRAKiT-style ASP.NET portals and drives the search
        form so the result table is in the DOM before we serialise it.
        The interaction is best-effort: if it fails or `url` isn't an
        eTRAKiT page, we fall through to the plain `page.content()` path.
        """
        assert self._context is not None

        page: Page = await self._context.new_page()
        try:
            response = await page.goto(url, wait_until="domcontentloaded")
            if response is None:
                raise ScrapeError(f"No response received for {url}")

            content_type = (response.headers.get("content-type") or "").lower()

            # Server actually serves a PDF behind an HTML-looking URL.
            if "application/pdf" in content_type:
                logger.info("URL %s served PDF via Content-Type, switching to PDF path", url)
                return await self._fetch_pdf(url, final_url=response.url)

            # Best-effort wait for any XHR-driven content to settle. We
            # swallow the timeout: many municipal sites keep long-lived
            # WebSockets open and would never reach `networkidle`.
            try:
                await page.wait_for_load_state("networkidle", timeout=10_000)
            except PlaywrightTimeoutError:
                logger.debug("networkidle wait timed out for %s; continuing", url)

            # Drive eTRAKiT-style portals to populate the results grid.
            # Returns iframe HTML when interaction successfully drove an
            # iframe; otherwise None and we fall back to `page.content()`.
            iframe_html: Optional[str] = None
            if self._looks_like_etrakit(url):
                iframe_html = await self._interact_etrakit(
                    page, url, params=etrakit_search,
                )
                logger.info(
                    "eTRAKiT interaction yielded_iframe_html=%s for %s",
                    iframe_html is not None, url,
                )

            html = iframe_html if iframe_html is not None else await page.content()
            final_url = page.url
            cleaned = self._clean_html(html)
            logger.debug("Captured %d chars of cleaned HTML from %s", len(cleaned), url)
            return FetchResult(
                url=url,
                final_url=final_url,
                content_type="html",
                text=cleaned[: self._settings.scraper_max_html_chars],
                raw_length=len(cleaned),
            )
        finally:
            await page.close()

    # ---- eTRAKiT helpers ----------------------------------------------

    @staticmethod
    def _looks_like_etrakit(url: str) -> bool:
        """Cheap URL-based heuristic. Avoids any DOM probing for non-eTRAKiT pages."""
        path = urlparse(url).path.lower()
        return any(marker in path for marker in _ETRAKIT_URL_MARKERS)

    async def _interact_etrakit(
        self,
        page: Page,
        url: str,
        *,
        params: Optional[EtrakitSearchParams] = None,
    ) -> Optional[str]:
        """Drive an eTRAKiT search and return the rendered HTML.

        eTRAKiT installs vary: some put the entire search UI on the
        main page; others embed it in an iframe (`cdMain` / `frmMain`
        / `frmContent`). Rather than guess from the URL or iframe
        name, we **adaptively locate the Search button** — scanning
        the main page first, then every sub-frame — and drive
        whichever scope owns it.

        `params` (optional) parameterises the search: when provided we
        fill the "Search By" dropdown, "Operator" dropdown, and value
        input before clicking. When omitted we do a blank-click
        (yields recent permits on permissive deployments, the empty
        marker on strict ones like Frisco).

        Returns
        -------
        * `str`  — iframe HTML when the search ran inside an iframe.
                   Caller should use it verbatim.
        * `None` — search ran on the main page (or interaction
                   failed). Caller falls back to `page.content()`.

        Always swallows exceptions; the pipeline degrades to plain
        capture rather than crashing.
        """
        interact_timeout_ms = 15_000

        try:
            # Locate the scope that actually contains the Search
            # button. Acts as our hydration signal: until the form is
            # in the DOM, eTRAKiT is still painting the login chrome.
            scope, scope_label = await self._locate_etrakit_search_scope(
                page, deadline_ms=15_000,
            )
            if scope is None:
                logger.warning(
                    "eTRAKiT: no Search button found on main page or any iframe for %s",
                    url,
                )
                self._log_frames(page, url)
                return None

            logger.info("eTRAKiT: Search button found in %s for %s", scope_label, url)

            if not await self._drive_etrakit_search(
                scope, interact_timeout_ms, url, params=params,
            ):
                logger.warning(
                    "eTRAKiT: interaction did not surface results for %s", url,
                )
                self._log_frames(page, url)
                await self._dump_debug_capture(page, url)
                return None

            logger.info("eTRAKiT: search results surfaced for %s", url)
            if isinstance(scope, Frame):
                return await scope.content()
            return None  # caller uses page.content()

        except PlaywrightTimeoutError as e:
            logger.warning("eTRAKiT interaction timed out on %s: %s", url, e)
            self._log_frames(page, url)
            return None
        except Exception as e:  # noqa: BLE001
            logger.warning("eTRAKiT interaction failed on %s: %s", url, e)
            self._log_frames(page, url)
            return None

    # ---- scope discovery + helpers -----------------------------------

    async def _locate_etrakit_search_scope(
        self, page: Page, *, deadline_ms: int,
    ) -> tuple[Page | Frame | None, str]:
        """Find the Page or Frame that contains the eTRAKiT Search button.

        Polls every 500ms until `deadline_ms` elapses. Main page wins
        ties: searching there avoids the cost of serialising an
        iframe and the risk of grabbing a sibling widget.

        Returns `(scope, label)` for logging, or `(None, "")` if not
        found within the budget.
        """
        poll_ms = 500
        elapsed = 0
        while elapsed < deadline_ms:
            # Main page first.
            for selector in _ETRAKIT_SEARCH_BUTTON_SELECTORS:
                try:
                    if await page.locator(selector).count() > 0:
                        return page, f"MAIN page via {selector!r}"
                except Exception:  # noqa: BLE001
                    continue
            # Then every sub-frame.
            for frame in page.frames:
                if frame is page.main_frame:
                    continue
                for selector in _ETRAKIT_SEARCH_BUTTON_SELECTORS:
                    try:
                        if await frame.locator(selector).count() > 0:
                            label = (
                                f"iframe name={frame.name!r} url={frame.url} "
                                f"via {selector!r}"
                            )
                            return frame, label
                    except Exception:  # noqa: BLE001
                        continue
            await page.wait_for_timeout(poll_ms)
            elapsed += poll_ms
        return None, ""

    def _log_frames(self, page: Page, url: str) -> None:
        """Emit the full frame inventory at WARNING — used on failure paths.

        This is the single most useful diagnostic when an unfamiliar
        eTRAKiT (or any iframe-based portal) won't yield results.
        """
        logger.warning("eTRAKiT: frame inventory for %s:", url)
        for i, frame in enumerate(page.frames):
            tag = " (MAIN)" if frame is page.main_frame else ""
            logger.warning(
                "  frame[%d]%s name=%r url=%s",
                i, tag, frame.name or "", frame.url or "",
            )

    async def _dump_debug_capture(self, page: Page, url: str) -> None:
        """Write current page + iframe HTML to disk for offline inspection.

        Triggered only on failure paths. Cheap insurance: when a new
        portal layout breaks our heuristics, this dump tells us in
        one round-trip what the scraper actually saw.
        """
        try:
            slug = re.sub(r"[^A-Za-z0-9]+", "_", urlparse(url).netloc)[:40] or "page"
            ts = int(time.time())
            main_path = Path(f"_debug_capture_{slug}_{ts}_main.html")
            html = await page.content()
            main_path.write_text(html, encoding="utf-8")
            logger.warning(
                "eTRAKiT: dumped main page HTML (%d chars) -> %s",
                len(html), main_path,
            )
            for i, frame in enumerate(page.frames):
                if frame is page.main_frame:
                    continue
                try:
                    fhtml = await frame.content()
                    fname = re.sub(r"[^A-Za-z0-9]+", "_", frame.name or f"frame{i}")[:40]
                    fpath = Path(f"_debug_capture_{slug}_{ts}_{fname}.html")
                    fpath.write_text(fhtml, encoding="utf-8")
                    logger.warning(
                        "eTRAKiT: dumped iframe %r (%d chars) -> %s",
                        frame.name, len(fhtml), fpath,
                    )
                except Exception as e:  # noqa: BLE001
                    logger.debug("eTRAKiT: could not dump iframe %r: %s", frame.name, e)
        except Exception as e:  # noqa: BLE001
            logger.debug("eTRAKiT: debug dump failed: %s", e)

    async def _drive_etrakit_search(
        self,
        scope: Page | Frame,
        timeout_ms: int,
        url: str,
        *,
        params: Optional[EtrakitSearchParams] = None,
    ) -> bool:
        """Click Search and wait for results inside `scope` (Page or Frame).

        Two modes:
          * Parameterised (params.is_active()): fill dropdowns + input,
            then click. Single attempt, since a user-supplied query
            shouldn't be silently retried with different defaults.
          * Blank (default): click as-is; on failure, pick a permissive
            "Search By" option and click again.
        """
        if params is not None and params.is_active():
            logger.info(
                "eTRAKiT: parameterised search on %s (search_by=%r operator=%r value=%r)",
                url, params.search_by, params.search_operator, params.search_value,
            )
            await self._fill_etrakit_form(scope, params)
            clicked = await self._click_first_match(
                scope, _ETRAKIT_SEARCH_BUTTON_SELECTORS, timeout_ms=3_000,
            )
            if not clicked:
                logger.warning("eTRAKiT: Search button not clickable after form fill on %s", url)
                return False
            return await self._wait_for_etrakit_results(scope, timeout_ms)

        # --- Blank-click fallback path (preserves prior behaviour). ---
        clicked = await self._click_first_match(
            scope, _ETRAKIT_SEARCH_BUTTON_SELECTORS, timeout_ms=3_000,
        )
        if clicked:
            logger.info("eTRAKiT: clicked Search on %s, waiting for results", url)
            if await self._wait_for_etrakit_results(scope, timeout_ms):
                return True
            logger.debug("eTRAKiT: first click yielded no grid; trying dropdown fallback")

        if await self._pick_first_etrakit_search_by(scope):
            clicked = await self._click_first_match(
                scope, _ETRAKIT_SEARCH_BUTTON_SELECTORS, timeout_ms=3_000,
            )
            if clicked and await self._wait_for_etrakit_results(scope, timeout_ms):
                logger.info("eTRAKiT: fallback dropdown+click succeeded on %s", url)
                return True

        return False

    async def _fill_etrakit_form(
        self, scope: Page | Frame, params: EtrakitSearchParams,
    ) -> None:
        """Fill the Search By / Operator / Value controls per `params`.

        Each step is best-effort: a missing dropdown (e.g. some
        municipal configs hide the Operator) does not abort the
        attempt. Logs at WARNING when an explicit param can't be
        applied so the operator can spot config drift.
        """
        if params.search_by:
            ok = await self._select_dropdown_label(
                scope, _ETRAKIT_SEARCH_BY_SELECTORS, params.search_by,
            )
            if not ok:
                logger.warning(
                    "eTRAKiT: could not apply search_by=%r", params.search_by,
                )

        if params.search_operator:
            ok = await self._select_dropdown_label(
                scope, _ETRAKIT_OPERATOR_SELECTORS, params.search_operator,
            )
            if not ok:
                # Operator dropdown is optional in many configs; debug-only.
                logger.debug(
                    "eTRAKiT: could not apply search_operator=%r (dropdown may be absent)",
                    params.search_operator,
                )

        if params.search_value:
            ok = await self._fill_first_match(
                scope, _ETRAKIT_SEARCH_INPUT_SELECTORS, params.search_value,
            )
            if not ok:
                logger.warning(
                    "eTRAKiT: could not type search_value=%r", params.search_value,
                )

    async def _select_dropdown_label(
        self, scope: Page | Frame, selectors: tuple[str, ...], label: str,
    ) -> bool:
        """Select an option by visible label; tolerant of case + whitespace.

        Tries `select_option(label=...)` exact match first (fast path),
        then enumerates options for a case-insensitive equality match,
        so callers can pass `"PERMIT NO"` or `"permit no"` and have
        either work.
        """
        for sel in selectors:
            try:
                dropdown = scope.locator(sel).first
                await dropdown.wait_for(state="visible", timeout=3_000)
            except PlaywrightTimeoutError:
                continue
            except Exception:  # noqa: BLE001
                continue

            try:
                await dropdown.select_option(label=label, timeout=2_000)
                logger.debug("eTRAKiT: selected %r in %r", label, sel)
                return True
            except Exception:  # noqa: BLE001
                pass

            try:
                options = await dropdown.locator("option").all_inner_texts()
                wanted = label.strip().lower()
                for opt in options:
                    if opt.strip().lower() == wanted:
                        await dropdown.select_option(label=opt, timeout=2_000)
                        logger.debug(
                            "eTRAKiT: selected %r (case-insensitive match for %r) in %r",
                            opt, label, sel,
                        )
                        return True
            except Exception as e:  # noqa: BLE001
                logger.debug("eTRAKiT: option enumeration failed on %r (%s)", sel, e)
            return False  # dropdown found but no matching option
        return False

    async def _fill_first_match(
        self, scope: Page | Frame, selectors: tuple[str, ...], value: str,
    ) -> bool:
        """Type `value` into the first visible matching `<input>`.

        Uses `fill()` (clears any existing content) rather than
        `type()` so re-running with a different value behaves
        idempotently.
        """
        for sel in selectors:
            try:
                el = scope.locator(sel).first
                await el.wait_for(state="visible", timeout=3_000)
                await el.fill(value, timeout=2_000)
                logger.debug("eTRAKiT: filled %r with %r", sel, value)
                return True
            except PlaywrightTimeoutError:
                continue
            except Exception as e:  # noqa: BLE001
                logger.debug("eTRAKiT: fill failed on %r (%s)", sel, e)
                continue
        return False

    async def _click_first_match(
        self, scope: Page | Frame, selectors: tuple[str, ...], *, timeout_ms: int,
    ) -> bool:
        """Click the first visible element matching any of `selectors`.

        Works on either a `Page` or a `Frame` (both expose `locator`
        and `wait_for_load_state`). After a successful click we briefly
        wait for `networkidle` *within the same scope* so ASP.NET
        WebForms postbacks (full or UpdatePanel/AJAX) have time to
        actually start firing before our caller checks for results.
        """
        for selector in selectors:
            try:
                locator = scope.locator(selector).first
                await locator.wait_for(state="visible", timeout=timeout_ms)
                await locator.click()
                logger.debug("eTRAKiT: clicked selector %r", selector)
                try:
                    await scope.wait_for_load_state("networkidle", timeout=8_000)
                except PlaywrightTimeoutError:
                    # Long-poll connections (common on portals) never
                    # reach networkidle; that's fine, downstream
                    # selector waits will handle it.
                    pass
                return True
            except PlaywrightTimeoutError:
                continue
            except Exception as e:  # noqa: BLE001
                logger.debug("eTRAKiT: selector %r unclickable (%s)", selector, e)
                continue
        return False

    async def _pick_first_etrakit_search_by(self, scope: Page | Frame) -> bool:
        """Pick a permissive default in the eTRAKiT 'Search By' dropdown."""
        preferred_labels = ("All", "Permit Type", "Date", "Permit Number", "Address")
        for selector in _ETRAKIT_SEARCH_BY_SELECTORS:
            try:
                dropdown = scope.locator(selector).first
                await dropdown.wait_for(state="visible", timeout=2_000)
                for label in preferred_labels:
                    try:
                        await dropdown.select_option(label=label, timeout=1_500)
                        logger.debug("eTRAKiT: selected 'Search By' = %r", label)
                        return True
                    except PlaywrightTimeoutError:
                        continue
                    except Exception:  # noqa: BLE001
                        continue
            except PlaywrightTimeoutError:
                continue
        return False

    async def _wait_for_etrakit_results(
        self, scope: Page | Frame, timeout_ms: int,
    ) -> bool:
        """Wait for results grid OR 'no records' marker to appear.

        Polls because we need to mix CSS-selector waits with
        Playwright's `text=` engine — a single `wait_for_selector`
        can't combine them. Returns True for either outcome (grid
        populated OR empty-state visible), since both prove the
        search round-tripped.
        """
        deadline_ms = timeout_ms
        poll_ms = 500
        elapsed = 0
        # CSS-based markers (positive and empty) checked in one shot.
        combined_css = f"{_ETRAKIT_RESULTS_SELECTOR}, {_ETRAKIT_EMPTY_SELECTOR}"

        while elapsed < deadline_ms:
            try:
                if await scope.locator(combined_css).count() > 0:
                    try:
                        await scope.wait_for_load_state("networkidle", timeout=5_000)
                    except PlaywrightTimeoutError:
                        pass
                    return True
            except Exception:  # noqa: BLE001
                pass
            # Text-based empty-state markers (Frisco, etc.).
            for text_sel in _ETRAKIT_EMPTY_TEXT_SELECTORS:
                try:
                    if await scope.locator(text_sel).count() > 0:
                        logger.info("eTRAKiT: empty-result marker matched %r", text_sel)
                        return True
                except Exception:  # noqa: BLE001
                    continue
            await scope.wait_for_timeout(poll_ms)
            elapsed += poll_ms
        return False

    async def _fetch_pdf(self, url: str, final_url: Optional[str] = None) -> FetchResult:
        assert self._context is not None
        logger.info("Downloading PDF: %s", url)
        # `request` shares cookies/UA with the browser context.
        response = await self._context.request.get(
            url,
            timeout=self._settings.scraper_nav_timeout_ms,
        )
        if not response.ok:
            raise ScrapeError(f"PDF download failed ({response.status}) for {url}")
        body = await response.body()

        try:
            reader = PdfReader(io.BytesIO(body))
            pages_text = []
            for page in reader.pages:
                try:
                    pages_text.append(page.extract_text() or "")
                except Exception:  # noqa: BLE001
                    # pypdf raises a zoo of exceptions per malformed page;
                    # skip individual pages rather than failing the doc.
                    continue
            text = "\n\n".join(pages_text).strip()
        except PdfReadError as e:
            raise ScrapeError(f"Could not parse PDF at {url}: {e}") from e

        if not text:
            raise ScrapeError(f"PDF at {url} contained no extractable text (scanned image?)")

        return FetchResult(
            url=url,
            final_url=final_url or url,
            content_type="pdf",
            text=text[: self._settings.scraper_max_html_chars],
            raw_length=len(text),
        )

    def _clean_html(self, html: str) -> str:
        """Strip boilerplate and collapse to readable text."""
        soup = BeautifulSoup(html, "lxml")
        for tag in soup(_BOILERPLATE_TAGS):
            tag.decompose()
        # Drop typical cookie/notice banners by id/class.
        for selector in ("#cookie-banner", ".cookie", ".banner", ".breadcrumb"):
            for el in soup.select(selector):
                el.decompose()
        text = soup.get_text(separator="\n", strip=True)
        # Collapse runs of blank lines so token spend stays sane.
        lines = [line for line in (ln.strip() for ln in text.splitlines()) if line]
        return "\n".join(lines)
